baseURL = "/"
languageCode = "sr-sr"
title = "Odluke zasnovane na podacima"
themesDir = "themes"
theme = "hugo-serif-theme"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.logo]
    mobile = "/images/Logo_kockasti_250_250.svg"
    standard  = "/images/Logo_kockasti_250_250.svg"
    alt = "Advanced Business Applications"

  [params.homepage_meta_tags]
    meta_description = "Nauka o podacima, veštačka inteligencija i mašinsko učenje u službi poslovanja"
    meta_og_title = "Budućnost poslovanja"
    meta_og_type = "website"
    meta_og_url = "https://hugo-serif.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

# Main Menu
[[menu.main]]
	name = "Usluge"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Projekti"
    url = "/team/"
    weight = 2

# Footer Menu
[[menu.footer]]
	name = "Početna"
	url = "/"
    weight = 1

[[menu.footer]]
	name = "Kontakt"
	url = "/contact/"
    weight = 2
